### PR TITLE
Feature/ephemeral storage

### PR DESCRIPTION
**Pull request by Meepit**
## Description
Adds the ability to set ephemeral_storage for the deployed lambda, using a newly added setting
```
{
   ...
   ephemeral_storage: { "Size": 1024 }
}
```
There has been a PR open for quite some time now https://github.com/zappa/Zappa/pull/1125 but it appears to have gone stale and the requested changes haven't been followed up on. I've added the requested tests in this PR.

## GitHub Issues
https://github.com/zappa/Zappa/issues/1120

### CODE REVIEW

**Review by elip-OE — COMMENTED** [review]
Looks good to me

**Review by monkut — APPROVED** [review]

**Comment by monkut** [comment]
@Meepit Can you check the testcase, it appears to be failing.

> FAILED tests/tests.py::TestZappa::test_load_settings_ephemeral_storage_overwrite - KeyError: 'ephemeral_storage'

**Comment by Meepit** [comment]
> @Meepit Can you check the testcase, it appears to be failing.
> 
> > FAILED tests/tests.py::TestZappa::test_load_settings_ephemeral_storage_overwrite - KeyError: 'ephemeral_storage'


@monkut  That's been fixed now, if you could please re-run the workflows 🙏

**Review by monkut — APPROVED** [review]

**Review by souravjamwal77 — APPROVED** [review]
Test cases passed. And I made a simple deployment using flask and changed ephemeral storage from 1024 to 512 and it got changes on console from 1024 to 512 MB.

**Pull request merged**
