### PR TITLE
Bypass python version runtime check when code run in docker

### PR DESCRIPTION
**Pull request by monkut**
## Description
Currently zappa performs a supported python version check on import.
In the case where zappa is used with docker, zappa will not allow unsupported python versions to be used.

This PR by-passes the full SUPPORTED_VERSION check on import when it detects that it is being run within docker and *ONLY* checks the `MINIMUM_SUPPORTED_MINOR_VERSION` (newly defined/added) when docker is detected.

This uses the `/proc/1/cgroup` check mentioned here to determine if code is being run in docker:
https://stackoverflow.com/a/20012536/24718

## GitHub Issues
https://github.com/zappa/Zappa/issues/1140

### CODE REVIEW

**Comment by souravjamwal77** [comment]
@monkut I think we need to merge master into this to keep it's code updated.

**Comment by monkut** [comment]
@souravjamwal77 There doesn't appear to be an issue in github. 
If you have time can you review the code?

**Review by souravjamwal77 — APPROVED** [review]
I couldn't test this inside the docker build because the aws-lambda image on the docker hub has no python3.10 version yet. If they publish a new version then I will test it out again. Approving for now.

**Review by goya813 — APPROVED** [review]
Looks Good!

**Pull request merged**
