### PR TITLE
Support AWS Lambdas ephemeral storage setting (#1120)

### PR DESCRIPTION
**Pull request by gbartosz**
## Description
Since march 2022 AWS allows for setting custom ephemeral storage size for Lambda (a storage mounted in a `/tmp` directory). Boto also supports this setting since v1.21.26.
This PR extends zappa_settings.json with `ephemeral_storage` key with default value of `{"Size": 512}`.

## GitHub Issues
https://github.com/zappa/Zappa/issues/1120

### CODE REVIEW

**Review by mdw123 — COMMENTED** [review]
I'm not a contributor to Zappa at this time, but I need this feature. This looks good to me, if I can help this PR along, I would be happy to spend some time on it.

**Review by elip-OE — COMMENTED** [review]
LGTM. tested on my environment with success.

Thanks!

**Comment by elip-OE** [comment]
Hi, Can we add it to next release?

**Review by elip-OE — COMMENTED** [review]
This works great!. please merge this PR

**Comment by elip-OE** [comment]
@gbartosz can you please run the above? many thanks!

**Review by monkut — CHANGES_REQUESTED** [review]
Can you add a testcase confirming that the given cli value is properly changed and doesn't exceed the max configurable ephemeral_storage value? (throws proper error

**Comment by monkut** [comment]
@elip-OE

Can you add a testcase confirming that the given cli value is properly changed and doesn't exceed the max configurable ephemeral_storage value? (throws proper error

**Comment by hellno** [comment]
Hi @gbartosz @elip-OE @mdw123
what is the status of this PR? I'm happy to merge it if we get the PR comment by @monkut in there.
(I've removed the `next-release-candidate` label because it's not a priority for the upcoming release, but we can get it done in the next or the one after if this is solved 🤩)

**Comment by Meepit** [comment]
Hi @hellno @monkut , I'm also quite keen on this feature. Given this PR seems to have gone stale, i've opened a new PR with the requested tests and validation here: https://github.com/zappa/Zappa/pull/1259

**Comment by monkut** [comment]
@Meepit Thanks for the PR update,  closing this one.

**Pull request closed without merging**
