### PR TITLE
Never use root logger to allow filtering zappa logs with greater ease

### PR DESCRIPTION
**Pull request by bagage**
## Description
 
It is a simple change to avoid using the root logger, so that upstream application can easily decide how to handle these specific logs while leaving root logger untouched.

### CODE REVIEW

**Review by monkut — APPROVED** [review]

**Comment by bagage** [comment]
I think the CI failed independently of my MR, should I do something @monkut?

**Comment by bagage** [comment]
Ping @monkut?

**Review by javulticat — APPROVED** [review]

**Comment by javulticat** [comment]
Hey @bagage, I came across this today, and it looked like the CI runners indeed had experienced some unrelated issue the first time they ran for your PR and you just needed someone to re-run the CI jobs for you.  So, I triggered the CI to run on your PR again, and everything came back green as expected.  So, I went ahead and merged this after giving the code a quick review myself.  Nice catch, and thanks for your contribution!

**Comment by bagage** [comment]
Awesome, thanks @javulticat :100:

**Pull request merged**
