### PR TITLE
Fix/Use aws_region in zappa_settings. Even if there is an os environment variable

### PR DESCRIPTION
**Pull request by kyaryunha**
## Description

Zappa README.md said 
```
"aws_region": "aws-region-name", // optional, uses region set in profile or environment variables if not set here
```

but if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are written in environment variables, zappa sets aws_region to AWS_DEFAULT_REGION in environment variables even if aws_region is written in zappa_settings.json.

## GitHub Issues

The issue below is also resolved by export AWS_DEFAULT_REGION=us-east-1 ,
The problem was caused by zappa importing the AWS_DEFAULT_REGION of the environment variable, not the aws_region of zappa_settings.

https://github.com/zappa/Zappa/issues/1215

### CODE REVIEW

**Comment by monkut** [comment]
@kyaryunha Thanks for the contribution.  

I think we can get this in the next release.
The linter is failing, you'll need to run `make black` / `make isort`.

**Comment by kyaryunha** [comment]
10 failed files of CI/CD are displayed. (Like the picture below.)
So if I do "make black", 10 files are changed.

But my "Files Changed" is only 1 file.

Should I commit all 10 codes of "make black"?
Or should I just commit the 1 file I did?

스크린샷 2023-03-02 오후 2 56 09

**Review by souravjamwal77 — CHANGES_REQUESTED** [review]
I think the error message could be like
`No aws_region found, set the aws_region in zappa_settings or Set the AWS_DEFAULT_REGION as env variable`

**Comment by kyaryunha** [comment]
@souravjamwal77

Thanks for the nice phrase recommendation! I'm not good at English.

`,` instead of `-` seems to be the zappa LookupError pattern,
In the expression you recommended, I'll changed `,` to `-`
I'll edit it to `No aws_region found - set the aws_region in zappa_settings or Set the AWS_DEFAULT_REGION as env variable` :D

**Review by monkut — APPROVED** [review]

**Review by monkut — CHANGES_REQUESTED** [review]
Sorry, can you add a testcase for this to assure that the newly added `LookUpError` is raised when the region is not defined?

**Comment by kyaryunha** [comment]
Ok, I will add test code next week.

**Comment by kyaryunha** [comment]
I tried to write a test code, but for some unknown reason, it didn't work.

I'll try again next week.

**Review by monkut — APPROVED** [review]

**Review by javulticat — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
