### PR TITLE
Add Support for Graviton 2 / ARM Architecture

### PR DESCRIPTION
**Pull request by NinitoAS**
## Description
This PR adds support for the 'new' Graviton 2 / ARM64 architecture. It builds on top of @[turingbeing](https://github.com/turingbeing)'s work (https://github.com/zappa/Zappa/pull/1057)

The new parameter is now a string instead of a list, defaulting to 'x86_64' if not defined.

Keep in mind that ARM64 is not supported in all regions. It is currently unsupported in the following regions: af-south-1, ap-east-1, ap-northeast-2, ap-northeast-3, ca-central-1, eu-south-1, eu-west-3, eu-north-1, me-south-1, sa-east-1 and us-west-1

It seems like AWS will fall back to x86 if the region does not support ARM.

@[hellno](https://github.com/hellno) can you review the PR?

AWS API [Docs](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#API_CreateFunction_RequestSyntax)

## GitHub Issues
Resolves: #1051

### CODE REVIEW

**Comment by NinitoAS** [comment]
@hellno, I know you are busy, but it would be great to have this merged before the next release

**Review by MaximeKlein — APPROVED** [review]

**Comment by monkut** [comment]
@NinitoAS Not sure why this go closed...

I'm looking at getting the next release out in Novemenber.
Can you fix the conflicts here, so we can get this merged in?

**Comment by sridhar562345** [comment]
@NinitoAS Can you post the status of this?

**Comment by monkut** [comment]
@NinitoAS can you fix the conflicts here?

**Comment by gaborschulz** [comment]
@monkut, is there anything I can support with on this issue?

**Pull request closed without merging**
