### PR TITLE
Troposphere library "AttributeError" fix and python3.9 runtime support

### PR DESCRIPTION
**Pull request by ghostmaster-ai**
## Description
zappa/core.py
method "add_description" in core.py line 2417 doesn't exists in the latest troposphere library, method "set_description" takes it's place. This change allows for "zappa deploy" and "zappa update" without errors.

## GitHub Issues
https://github.com/zappa/Zappa/issues/1016
https://github.com/zappa/Zappa/issues/1002
https://github.com/zappa/Zappa/issues/1000

### CODE REVIEW

**Review by justinwride — APPROVED** [review]
Yes please 🙏

**Comment by willfranklyn** [comment]
This would be huge!

**Comment by code-leen** [comment]
This would be **LIT** 🔥

**Comment by thathert** [comment]
Yes, please! The old solution we had was to pin tropo to 2.7.0 but with the latest major version of setuptools (58.0+) conflicts with troposphere 2.7.0 because setuptools dropped support for `use2to3` ([issue](https://github.com/pypa/setuptools/issues/2769)). We can always pin setuptools to <58, but this would be a much better alternative. 🙌

**Comment by onimitch** [comment]
Thanks for this fix @ghostmaster-ai, I just switched to your fork until a new official release is published

**Comment by tyoc213** [comment]
It isnt the same as this one? https://github.com/zappa/Zappa/pull/1026

**Comment by arundas1903** [comment]
Can some one look into this and close the PR? We are stuck with this!!! :(

**Review by arundas1903 — APPROVED** [review]

**Comment by hellno** [comment]
Hey everyone, a team of contributors is back to support the amazing Zappa project. 
The short term goal is to bring back CI releases and merge urgent bug fixes this week.
This would allow everyone to continue (or come back) to using this repo.

https://github.com/zappa/Zappa/pull/1026 is the active PR to watch for Python 3.9 support

I'm closing this PR as it's not relevant anymore

**Pull request closed without merging**
