### PR TITLE
Add Support for Graviton 2 / ARM `Architectures`

### PR DESCRIPTION
**Pull request by turingbeing**
## Description
This PR adds support for Graviton 2 / ARM64 Lambda's. It adds a new `architectures` configuration option, which defaults to `x86_64`. This parameter is also used for correct architecture wheel selection.

This is my first submission to Zappa, so please do CR and feedback anything I might have missed, or need to do.

AWS API [Docs](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#API_CreateFunction_RequestSyntax)

## GitHub Issues

Resolves: https://github.com/zappa/Zappa/issues/1051

### CODE REVIEW

**Comment by turingbeing** [comment]
I'll work on this at the weekend, been busy!

**Comment by hootisfix** [comment]
@turingbeing , do you need help on this PR ?

**Comment by Hazealign** [comment]
I want to use this feature. How can I help this to get merged?

**Comment by turingbeing** [comment]
> I want to use this feature. How can I help this to get merged?

You should be able to use it from the branch without merging it, just needs some minor refactoring, but been mega busy with life and work to do it

**Comment by turingbeing** [comment]
Actually I think it's here: https://github.com/zappa/Zappa/pull/1123

**Comment by monkut** [comment]
@turingbeing Looks like this would be nice to get merged in.

Do you have time to address the comments in the coming months?

**Comment by monkut** [comment]
This PR is further along, closing this one.

https://github.com/zappa/Zappa/pull/1123

**Pull request closed without merging**
