### PR TITLE
Add Support for Manylinux 2_28 build libraries

### PR DESCRIPTION
**Pull request by phil-airship**
Had added support for Manylinux 2_24 in 2021:
https://github.com/zappa/Zappa/pull/1083

But that version is EoL and Python Cryptography has moved to Manylinux 2_28.
https://github.com/pypa/manylinux

Updating to support while maintaining backwards compatibility.

Tested on Lambda an encountered no issues

### CODE REVIEW

**Comment by sridhar562345** [comment]
@phil-airship 
Seems like some packages are publishing abi3 manylinux wheels in below format
```
pycryptodome-3.16.0-cp35-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
```
Our current regex is not matching this kind of file, Can you verify whether we need to update the regex or not?

**Comment by sridhar562345** [comment]
According to [pypa/manylinux](https://github.com/pypa/manylinux) PEP 600 has been designed to be "future-proof" and does not enforce specific symbols and a specific distro to build. It only states that a wheel tagged manylinux_x_y shall work on any distro based on glibc>=x.y

These are the current glibc versions in lambda runtimes.

Python | glibc
-- | --
python3.7 | 2.17
python3.8 | 2.26
python3.9 | 2.26
python3.10 | 2.26

  
So I guess the 2_28 manylinux wheels may not work on lambda yet.

**Comment by sridhar562345** [comment]
@phil-airship 
I have tested your PR with Cryptography 40.0.0 and I am facing issues related to GLIBC
```
{
  "errorMessage": "Unable to import module 'lambda_handler': /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /opt/python/cryptography/hazmat/bindings/_rust.abi3.so)",
  "errorType": "Runtime.ImportModuleError",
  "stackTrace": []
}
```

**Comment by siddharthak024** [comment]
> @phil-airship I have tested your PR with Cryptography 40.0.0 and I am facing issues related to GLIBC
> 
> ```
> {
>   "errorMessage": "Unable to import module 'lambda_handler': /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /opt/python/cryptography/hazmat/bindings/_rust.abi3.so)",
>   "errorType": "Runtime.ImportModuleError",
>   "stackTrace": []
> }
> ```

Is this issue resolved

**Pull request closed without merging**
