### PR TITLE
Pinning Troposphere for breaking change

### PR DESCRIPTION
**Pull request by mcrowson**
## Description
Troposphere had a breaking change and we were not pinning a version for it. 

## GitHub Issues
#999 #1001 #1013 #1016

https://github.com/cloudtools/troposphere/blob/main/CHANGELOG.rst#300-20210705

### CODE REVIEW

**Review by ian-whitestone — APPROVED** [review]

**Review by BigHealthDanverBraganza — APPROVED** [review]
LGTM

**Comment by markpeek** [comment]
@mcrowson I received this [troposphere issue](https://github.com/cloudtools/troposphere/issues/1952) today. tl;dr: the recently released setuptools >= 58.0.0 removed 2to3. This means troposphere 2.7 cannot be used with Python 3 using the newer setuptools.

It would be good to merge this PR and do a release of zappa to support users needing Python 3 compatibility.

**Comment by AlmogCohen** [comment]
I don't this fix was released to `pip` yet....fresh zappa installations still encounter this issue

**Comment by armando-herastang** [comment]
Is there an ETA on the release containing these changes?

**Comment by frakes413** [comment]
For those who need a bandaid for this, just point to current master branch of this repository in your requirements files -
`git+git://github.com/zappa/Zappa.git@master#egg=zappa`. More info on this kind of thing here -> [https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source](url)

**Pull request merged**
