### PR TITLE
Fix async invocation in Python 3

### PR DESCRIPTION
**Pull request by suriya**
## Description

Removed the encoding of the json message for SNS notification when sys.version is Python 3.

See https://github.com/Miserlou/Zappa/pull/1331

This issue and similar pull request have been open for more than three years. Please accept and merge them into Zappa.

## GitHub Issues
https://github.com/Miserlou/Zappa/issues/1323

### CODE REVIEW

**Comment by wangsha** [comment]
I had the same issue and confirm this solution works.

**Review by hellno — APPROVED** [review]
Looks great 👍🏽 Thanks for the contribution

**Comment by sako0938** [comment]
Just hit this error today, cant wait for the merge!

**Comment by kornpow** [comment]
I was able to build this into a wheel and test it out! Once I got it installed properly I was able to get my function to call SNS
```
@task_sns
def longrunner(delay, msg):
    sleep(float(delay))
    return f"testing task: {msg}"
```

**Pull request merged**
